import mongoose from "mongoose";


const productSchema=mongoose.Schema({
    name:{
        type:String,
        require:true,
    },
    description:{
        type:String,
        require:true
    },
    images:[
        {
            type:String,
            required:true,
        }
    ],
    brand:{
        type:String,
        default:""
    },
    price:{
        type:Number,
        default:0
    },
    oldPrice:{
        type:Number,
        default:0
    },
    catName:{
        type:String,
        default:''
    },
    carId:{
        type:String,
        default:""
    },
    subCatId:{
        type:String,
        default:'',
    },
    subCatId:{
        type:String,
        default:''
    },
    subCat:{
        type:String,
        default:''
    },
    subCatName:{
        type:String,
        default:""
    },
    thirdsubCat:{
        type:String,
        default:""
    },
    thirdsubCatName:{
        type:String,
        default:""
    },
    category:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Category',
        required:true,
    },
    countInStock:{
        type:Number,
        required:true,
    },
    rating:{
        type:Number,
        default:0
    },
    isFeatured:{
        type:Boolean,
        default:false
    },
    discount:{
        type:Number,
        required:true,
    },
    productRam:[
        {
            type:String,
            default:null
        }
    ],
    size:[
        {
            type:String,
            default:null
        }
    ],
    productWeight:[
        {
            type:String,
            default:null,
        }
    ],
    location:[
        {
            value:{
                type:String,
            },
            label:{
                type:String,
            }
        },
    ],
    dateCreated:{
        type:Date,
        default:Date.now,
    }
})

productSchema.virtual('id').get(function(){
    return this._id.toHexString();
})

productSchema.set('toJSON',{
    virtual:true
})

exports.Product= mongoose.model('Product',productSchema)